# Generated by Django 2.2.2 on 2020-05-02 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0010_auto_20200427_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_extravio',
            fields=[
                ('identificativo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.datetime(2020, 5, 2, 18, 28, 14, 180358, tzinfo=utc))),
                ('descripcion', models.TextField(default='Sin descripcion', max_length=400)),
                ('nombre_animal', models.CharField(max_length=20)),
                ('animal', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=20)),
                ('edad_animal', models.CharField(max_length=20)),
                ('numero_telefono_persona', models.IntegerField(default=' ')),
                ('latitud_perdido', models.FloatField()),
                ('longitud_perdido', models.FloatField()),
                ('imagen', models.ImageField(default='imagenes/None/no-img.jpg', upload_to='images/')),
                ('ip_dispositivo', models.CharField(max_length=20)),
                ('encontrado', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 5, 2, 18, 28, 14, 176380, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='datos_adopcion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 5, 2, 18, 28, 14, 178494, tzinfo=utc)),
        ),
    ]
